import { getAwsDatabaseProjectMock } from '@tests/mocks/project'
import { PROVIDER, SERVICE_TYPE } from '@src/constants'
import { ENVIRONMENT } from '@src/project/constants'
import type { ProjectConfiguration } from '@src/project/types'
import { getAutoGeneratedAttributes } from '../getAutoGeneratedAttributes'

describe('Auto generated attributes for services', () => {
  describe('state attributes', () => {
    let project: ProjectConfiguration

    beforeEach(() => {
      project = getAwsDatabaseProjectMock()
    })

    it('provides all the attributes needed', () => {
      const stateAttributes = getAutoGeneratedAttributes(
        SERVICE_TYPE.STATE,
        project,
        ENVIRONMENT.PRODUCTION,
      )

      expect(stateAttributes).toEqual(
        expect.objectContaining({
          bucket: project.state.bucket,
          statePath: project.state.statePath,
          lockTable: project.state.lockTable,
          type: SERVICE_TYPE.STATE,
          provider: PROVIDER.AWS,
          name: expect.stringContaining('state'),
        }),
      )
    })
  })

  describe('cluster attributes', () => {
    it.todo('is pending')
  })

  describe('dns attributes', () => {
    it.todo('is pending')
  })
})
